### ISSUE TITLE
Questions and possible issues regarding the HF patch v3.12

### ISSUE THREAD

**Issue by ghost** [ManlyMarco/KK-HF_Patch#34]
First time posting here so I hope I'm doing it right.

In charamaker, turning off the 'sub' acc category on the right side of the window turns itself back on when I select another acc slot. I am talking about the general option.

During H, turned off a bag accessory. It turns itself back on when I change the clothes state to any of them. The card used was a vanilla, not edited in any way.

In charastudio, the scene load list resets my page. If I deleted a scene on page 5 I'm sent back to page 1. Also on studio run next time I get a different page as a starting point.

Translation issue, all personalities get bad translations for the choice answers. Happens randomly but more often than not.
Logo and the main menu theme image translation are not included in the patch.

RealPOV plugin, I suggest to set the default values to FOV:40-45 range, offsetz to 0.06 and showing the head for the best pov experience. Issue the plugin has is whenever I turn it on and off and also change the map location or just the H position, the neck's shadow gets crushed.

Animation loader or just broken kplug animations, many of the seated positions lose the chair during it, so the character hangs in the air. Also the penis on 'cum outside' choice, bends on some positions. Character heights didn't go much from the default 30f/60m values so it can't be that.
Position names have 2x standing doggystyle and 2x reverse cowgirl but are different.

BP plugin and mods version v4.2 in the patch, as well as the new v4.3 don't work right. Reverting back to v4.1 solved the issues it caused in most cases. It messes with poses done in newer and older scenes, there were mentions of this on 4chan for many users. Happened to me too.
I'd also recommend excluding the BP uncensors as part of the UncensorSelector modpack because plugin to mod version difference when comparing the KK Manager version and the actual release can cause issues, as I believe the creator himself said so on his github page.

Do you know which setting or plugin changes the panties clothes states to both legs, instead of the hanging on one leg, one? How do I remove this?

Thank you for your work.

**Comment by ManlyMarco** [comment]
> First time posting here so I hope I'm doing it right.

Generally it's better to report issues to creators of the problematic plugins/mods directly since that's what I'm going to do anyways in most cases. They might want to ask you to test something and it's harder to do through me (ideally we could talk on the discord server).

> In charamaker, turning off the 'sub' acc category on the right side of the window turns itself back on when I select another acc slot. I am talking about the general option.
> 
> During H, turned off a bag accessory. It turns itself back on when I change the clothes state to any of them. The card used was a vanilla, not edited in any way.
Probably caused by KK_AccStateSync, it can be turned off in maker if needed or the plugin can be removed.

> In charastudio, the scene load list resets my page. If I deleted a scene on page 5 I'm sent back to page 1. Also on studio run next time I get a different page as a starting point.

Unlikely to be fixed, when removing multiple scenes I suggest opening the folder and doing it in explorer.

> Translation issue, all personalities get bad translations for the choice answers. Happens randomly but more often than not.

What version of the game do you have? Can you give an example and how to reproduce?

> Logo and the main menu theme image translation are not included in the patch.

This is on purpose to keep the original branding.

> RealPOV plugin, I suggest to set the default values to FOV:40-45 range, offsetz to 0.06 and showing the head for the best pov experience. Issue the plugin has is whenever I turn it on and off and also change the map location or just the H position, the neck's shadow gets crushed.

I was just updating his plugin, I'll change defaults to something similar.

> Animation loader or just broken kplug animations, many of the seated positions lose the chair during it, so the character hangs in the air. Also the penis on 'cum outside' choice, bends on some positions. Character heights didn't go much from the default 30f/60m values so it can't be that.
> Position names have 2x standing doggystyle and 2x reverse cowgirl but are different.

Animation Loader is used by a couple of modders, many of the animations are completely original. It doesn't support props so far it looks like, I'll ask but it might be better to start an issue directly [here](https://github.com/Keelhauled/KeelPlugins/issues).

> BP plugin and mods version v4.2 in the patch, as well as the new v4.3 don't work right. Reverting back to v4.1 solved the issues it caused in most cases. It messes with poses done in newer and older scenes, there were mentions of this on 4chan for many users. Happened to me too.

What exactly is the issue? Did you make sure you didn't have duplicate BP uncensors in your mods folder? I've not seen or heard about this so far, most people with issues mixed up plugin and mod versions.

> I'd also recommend excluding the BP uncensors as part of the UncensorSelector modpack because plugin to mod version difference when comparing the KK Manager version and the actual release can cause issues, as I believe the creator himself said so on his github page.

This is on the modpack maintainer, removing them is something planned for the future.

> Do you know which setting or plugin changes the panties clothes states to both legs, instead of the hanging on one leg, one? How do I remove this?

Sounds like the character uses a panty variant with different half-off state.

> Thank you for your work.

Thanks for the feedback!

**Comment by ManlyMarco** [comment]
I linked to the wrong repo for the AnimationLoader, [this](https://github.com/IllusionMods/AnimationLoader/issues/) is the correct one, there's an issue about this too.

**Comment by Mysterydoge** [comment]
Hello again.

I originally asked about these 'issues' on 4chan's KK threads first since I wasn't sure if they're easily fixable or just a bad setting somewhere. Lack of a proper response got me here, and I do not have a Discord account. I do apologize if I wrote about it in the wrong place.

KK_AccStateSync is indeed the cause of the first two cases, and I haven't noticed a setting to disable this behavior. Removed it.

Studio scene removal from the list, it happens even if I remove only 1 scene, it sends me back to page 1 and the next time I start from a different page. I can't be sure it behaved like this before but if you're saying it can't be fixed, moving on.

Version of the game? I was using an older repack RX version, can't remember which since I shortened the folder name but it has all the DLCs incl darkness and yoyaku, on top of which I installed the patch with the clear everything option turned on.
It happens with the gossip option, mainly when the girl is a friend, yellow bar. Choices shown look like machine translation more often than not and it happens to multiple personalities. This was the case with the previous patch version as well.

BP plugin and mods, for some of the few scenes I had, like reactions or one with a girl in a box, their pose displayed completely different than what was on the scene pic, hands misplaced and T-posing in some cases. The v4.3 didn't solve this, but downgrading to v4.1 did and I made sure to remove all existing mods and the plugin beforehand, as was stated on the page. The plugin creator says that the v4.2 version is bugged.
I realize this is a probably a very bad explanation but the anons on 4chan suggested this and it worked. Issues mentioned are I believe 3 threads older than the current one, if you're willing to check.

Panties states, I don't have that plugin. Used item's name is the vanilla game's lace topped panties but with a 'Na' at the bottom right of the thumbnail. Character, the 'motherly' personality one. What does the 'Na' stand for if I may ask? Other vanilla panties have those initials as well.
My OC uses omega's panties mod with the default state, on one leg only.

I'll check the AL one next, can pictures be posted on git, as .zip at least? Easier to show what I mean.

**Comment by ManlyMarco** [comment]
> I originally asked about these 'issues' on 4chan's KK threads first since I wasn't sure if they're easily fixable or just a bad setting somewhere. Lack of a proper response got me here, and I do not have a Discord account. I do apologize if I wrote about it in the wrong place.

Posting on github is fine, but it usually doesn't get checked very often. If you want something fixed then talking on discord is the best way to do it. Most modders don't check 4chan so any bug reports there are only heard if someone reposts it on discord or github like this.

> -Update, just tested this without mods and it doesn't jump to page 1, it's a plugin causing this.

Probably BrowserFolders, it reloads the list to make subfolders work so that might be a side effect.

> Version of the game, I was using an older repack RX JP version, can't remember which since I shortened the folder name but it has all the DLCs incl darkness and yoyaku, on top of which I installed the patch with the clear everything option turned on.
> It happens with the gossip option, mainly when the girl is a friend, yellow bar. Choices shown look like machine translation more often than not and it happens to multiple personalities. This was the case with the previous patch version as well.

Sounds like an old bug that should have been fixed a few versions of BR/HF ago. Update and see if it persists.

> BP plugin and mods, for some of the few scenes I had, like reactions or one with a girl in a box, their pose displayed completely different than what was on the scene pic, hands misplaced and T-posing in some cases. The v4.3 didn't solve this, but downgrading to v4.1 did and I made sure to remove all existing mods and the plugin beforehand, as was stated on the page. The plugin creator says that the v4.2 version is bugged.

A fixed version should be released soon.

> Panties states, I don't have that plugin. Used item's name is the vanilla game's lace topped panties but with a 'Na' at the bottom right of the thumbnail. Character, the 'motherly' personality one. What does the 'Na' stand for if I may ask? Other vanilla panties have those initials as well.
> My OC uses omega's panties mod with the default state, on one leg only.
> -Update, Installed the plugin and can confirm, all 'Na' initialed vanilla game panties have the altered half state, blacklist points to the game files and not a mod sooo...what do I do now?

There are zipmods that add stock item versions with different half-off look, sounds like you are using that. Use the base version instead without the 'Na' postfix. This is something in the model/asset itself and can't be changed at runtime.

> I'll check the AL one next, can pictures be posted on git, as .zip at least? Easier to show what I mean.

You can drag files in the text editor.

**Comment by Mysterydoge** [comment]
> Sounds like an old bug that should have been fixed a few versions of BR/HF ago. Update and see if it persists.
Didn't happen on the repack I was using, which was either rx8 or rx9. Started appearing when I tried out the previous patch version, and still persists with the current one. What do I need to update?

> There are zipmods that add stock item versions with different half-off look, sounds like you are using that. Use the base version instead without the 'Na' postfix. This is something done in the model/asset itself and can't be changed at runtime.
Ok, can you please tell me exactly which mod is responsible for this change? Again, blacklist plugin didn't help and I've no idea which zipmod to remove.

Last one of these, do you happen to know if the defaultparameditor includes the 'vignette' when saving the parameters in studio? Saving it and then either restarting studio or using the scene reset button, keeps resetting the vignette to 'on' even though I've saved with it being 'off'. Pressing the load parameters button works fine however.

**Comment by ManlyMarco** [comment]
> > Sounds like an old bug that should have been fixed a few versions of BR/HF ago. Update and see if it persists.
> 
> Didn't happen on the repack I was using, which was either rx8 or rx9. Started appearing when I tried out the previous patch version, and still persists with the current one. What do I need to update?

Latest patch should work fine, I didn't see any issues with untranslated options in a while now. I can't really help much other than tell you to try updating translation-related plugins and comparing translation folders to the one in BR (they should be more or less the same). If you manage to find the cause I'd be very interested in learning about it.

> > There are zipmods that add stock item versions with different half-off look, sounds like you are using that. Use the base version instead without the 'Na' postfix. This is something done in the model/asset itself and can't be changed at runtime.
> 
> Ok, can you please tell me exactly which mod is responsible for this change? Again, blacklist plugin didn't help and I've no idea which zipmod to remove.
> -Edit, to clarify, it's the base versions themselves located at the top of the list, that now have this 'Na' in their thumb. There are no other versions, maker search names don't show any. Pic related.
> ![pic](https://user-images.githubusercontent.com/89920337/132062211-b8d803f9-b449-41a6-9a22-02c17ec08772.JPG)

It's apparently ` [nakay] Zuri sage shorts v1.2`, it got included in the modpack by accident and will be removed on next update.

> Last one of these, do you happen to know if the defaultparameditor includes the 'vignette' when saving the parameters in studio? Saving it and then either restarting studio or using the scene reset button, keeps resetting the vignette to 'on' even though I've saved with it being 'off'. Pressing the load parameters button works fine however.

Sounds like a bug in the plugin if it works sometimes, maybe it tries to set the value too early. It's a Keel's plugin so you can report it on the repo, although he went into hibernation.

**Comment by Mysterydoge** [comment]
Okay, can confirm that the nakay's mod changed the clothing state.

For translations, I don't know how to do this, and I don't have anything from BR, only yours. 
I updated to the latest auto translator plugin and checked and captured the cases I'm experiencing. I've also checked and named them with the personality they belong to so please check them out.
[Bad choices translation.zip](https://github.com/ManlyMarco/KK-HF_Patch/files/7110434/Bad.choices.translation.zip)

I will go to his AL and DPE pages next. 

Also, do I close this issue once we're finished or do you do that? I have a 'close with comment' option, is that it?

**Comment by Mysterydoge** [comment]
Without opening it as a new issue, KKAPI's card author history can be deleted with the AccStateSync plugin. Apparently you only need to load a card with that filter turned on and it's gone.

**Comment by ManlyMarco** [comment]
Can you try [this](https://cdn.discordapp.com/attachments/446868355828416523/883962718351159326/en.7z) translation\en folder instead of the one in the patch and see if the choices are still broken?

**Comment by Mysterydoge** [comment]
Tried it out as is. Result is still the same as the .zip pics + Honest definitely has missing lines (e.g. the entire conversation where she asks about joining the club, and asks again to become a lover are both untranslated). Will check without zzzMachine .zip now.

**Comment by Mysterydoge** [comment]
RealPOV + Animation Loader.
Service -> Mouth -> Lying Mouth F*ck position, the male's pov inverts the camera mouse movements.

**Comment by ManlyMarco** [comment]
What swap are you talking about? What exactly did you do?

**Comment by ManlyMarco** [comment]
The missing lines will be fixed in an upcoming translation update.
